name: Build
on:
  push:
    branches-ignore:
      - 'main'
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: install and build
        run: |
          yarn
          yarn run build
        env:
          CI: false